### DISCUSSION TITLE
Installing Sunbird-ed 7.5 in OCI

### DISCUSSION THREAD

**Discussion by simhead** [Sunbird-Ed/Community#773] [Contribution]
This is the placeholder and contains the list of activities done to install Sunbird-ed 7.5 in Oracle OCI platform:

Main tasks performed:
- added/updated global-values.yaml:
```
  domain: "sunbird-ed.<domain>"
  sunbird_cloud_storage_provider: aws

 # OCI S3 Compartible API Details
  s3_access_key: "zzzz"
  s3_secret_key: "zzzz"
  s3_secret_id: "zzz"
  s3_endpoint: "https://<ns>.compat.objectstorage.<region>.oraclecloud.com"
  s3_path_style_access: "true"
  s3_region: "us-ashburn-1"

  # OCI Ally user details:
  username: API_USER_sunbird-ed-app1
  user_ocid: ocid1.user.oc1..
  user_tenancy: ocid1.tenancy.oc1..
  user_fingerprint: 4a:05:71:50:77
  user_region: us-ashburn-1
  user_key_file: /root/.oci/bastion.key
  user_key_file_pem: "-----BEGIN RSA PRIVATE KEY----------END RSA PRIVATE KEY-----\\nOCI_API_KEY"
  private_subnet_ocid: ocid1.subnet.oc1.iad.
```
- added/updated global-cloud-values.yaml
```
  oci_public_container_name: storage_container_public
  oci_private_container_name: storage_container_private
  oci_reports_container_name: reports_container_private
  oci_flink_state_container_name: flink_state_container_private
  oci_dial_state_container_name: dial_state_container_public
  oci_backups_container_name: backups_container_private
  oci_telemetry_container_name: telemetry_container_private
  private_ingressgateway_ip: 10.96.14.21
```
- updated global-values-jwt-tokens.yaml, global-values-rsa-keys.yaml for new tokens and keys

List will expand from here onwards.

**Comment by simhead** [comment]
Here are some more activities done for OCI revamp:
- oci storage class for pvc - changed to  'oci-bv' 
- DB backups
```
Redis: tweaked image used by cronjob to use oci command and upload to oci object storage
image: repository: "simhead00/redis-backup" pullPolicy: IfNotPresent imagePullSecrets: "" tag: "0.0.1"

Postgres: same applies here
image: repository: "simhead00/postgres-backup" pullPolicy: IfNotPresent imagePullSecrets: "" tag: "0.0.1"

NOTE: in order to get oci cli to work, "oci-config-cm.yaml" - configmap has been added
```
-

**Comment by simhead** [comment]
and here are the contents for oci-config-cm.yaml"
```
apiVersion: v1
data:
  fingerprint: <encoded fingerprint
  region: <encoded region>
  tenancy: <encoded tenancy>
  user: <encoded user>
kind: Secret
metadata:
  name: oci-config

---
apiVersion: v1
data:
  oci_api_key.pem: <encoded private key>
kind: Secret
metadata:
  name: oci-key-file
```
